// data.js
const BIN_ID = '6a032c1ec0954111d81145d6'; 
const API_KEY = '$2a$10$n74BprduBaxkWLZ72Jok.uusA4D.MrzIci5phXRfa71Kr5fsLBJQu';

const ingredienti = [
    { cat: "PASTA", color: "var(--cat-pasta)", nome: "Palline normali", fer: 100, we: 250 },
    { cat: "PASTA", color: "var(--cat-pasta)", nome: "Palline canapa", fer: 15, we: 30 },
    { cat: "PASTA", color: "var(--cat-pasta)", nome: "Mezzi", fer: 2, we: 10 },
    { cat: "VASCHETTE", color: "var(--cat-vaschette)", nome: "Melanzane", fer: 1, we: 2 },
    { cat: "VASCHETTE", color: "var(--cat-vaschette)", nome: "Zucchine", fer: 1, we: 2 },
    { cat: "VASCHETTE", color: "var(--cat-vaschette)", nome: "Peperoni", fer: 1, we: 2 },
    { cat: "VASCHETTE", color: "var(--cat-vaschette)", nome: "Funghi", fer: 1, we: 2 },
    { cat: "VASCHETTE", color: "var(--cat-vaschette)", nome: "Forno", fer: 1, we: 1 },
    { cat: "VASCHETTE", color: "var(--cat-vaschette)", nome: "Fritte", fer: 1, we: 2 },
    { cat: "VASCHETTE", color: "var(--cat-vaschette)", nome: "Salsa", fer: 1, we: 2 },
    { cat: "VASCHETTE", color: "var(--cat-vaschette)", nome: "Asparagi I.G.P.", fer: 1, we: 2 },
    { cat: "FORMAGGI", color: "var(--cat-formaggi)", nome: "Mozzarella in kg", fer: 15, we: 40 },
    { cat: "FORMAGGI", color: "var(--cat-formaggi)", nome: "Bufala", fer: 5, we: 15 },
    { cat: "FORMAGGI", color: "var(--cat-formaggi)", nome: "Provola aff.", fer: 2, we: 5 },
    { cat: "FORMAGGI", color: "var(--cat-formaggi)", nome: "Burrata", fer: 5, we: 10 },
    { cat: "FORMAGGI", color: "var(--cat-formaggi)", nome: "Casatella", fer: 1, we: 3 },
    { cat: "FORMAGGI", color: "var(--cat-formaggi)", nome: "Ricotta", fer: 1, we: 2 },
    { cat: "FORMAGGI", color: "var(--cat-formaggi)", nome: "NO lattosio", fer: 1, we: 2 },
    { cat: "FORMAGGI", color: "var(--cat-formaggi)", nome: "Parmigiano 24m", fer: 1, we: 1 },
    { cat: "FORMAGGI", color: "var(--cat-formaggi)", nome: "Brie", fer: 1, we: 1 },
    { cat: "FORMAGGI", color: "var(--cat-formaggi)", nome: "Gorgonzola", fer: 1, we: 1 },
    { cat: "FORMAGGI", color: "var(--cat-formaggi)", nome: "Asiago", fer: 0.5, we: 1 },
    { cat: "FORMAGGI", color: "var(--cat-formaggi)", nome: "Pecorino", fer: 1, we: 2 },
    { cat: "SALUMI", color: "var(--cat-salumi)", nome: "Salsiccia", fer: 2, we: 10 },
    { cat: "SALUMI", color: "var(--cat-salumi)", nome: "Pancetta", fer: 0.5, we: 1 },
    { cat: "SALUMI", color: "var(--cat-salumi)", nome: "Salamino num", fer: 2, we: 5 },
    { cat: "SALUMI", color: "var(--cat-salumi)", nome: "Porchetta", fer: 1, we: 1 },
    { cat: "SALUMI", color: "var(--cat-salumi)", nome: "Roastbeef", fer: 0.5, we: 1 },
    { cat: "SALUMI", color: "var(--cat-salumi)", nome: "Prosciutto cotto", fer: 1, we: 1 },
    { cat: "SALUMI", color: "var(--cat-salumi)", nome: "Sopressa", fer: 0.5, we: 1 },
    { cat: "SALUMI", color: "var(--cat-salumi)", nome: "Speck", fer: 1, we: 1 },
    { cat: "SALUMI", color: "var(--cat-salumi)", nome: "Mortadella", fer: 1, we: 1 },
    { cat: "SALUMI", color: "var(--cat-salumi)", nome: "Prosciutto Crudo", fer: 1, we: 1 },
    { cat: "SALUMI", color: "var(--cat-salumi)", nome: "Wurstel", fer: 2, we: 5 },
    { cat: "SALUMI", color: "var(--cat-salumi)", nome: "Bresaola", fer: 1, we: 1 },
    { cat: "SCAFFALERIA", color: "var(--cat-scaffaleria)", nome: "Uova bio", fer: 6, we: 12 },
    { cat: "SCAFFALERIA", color: "var(--cat-scaffaleria)", nome: "Pesto", fer: 1, we: 1 },
    { cat: "SCAFFALERIA", color: "var(--cat-scaffaleria)", nome: "Pistacchio", fer: 1, we: 1 },
    { cat: "SCAFFALERIA", color: "var(--cat-scaffaleria)", nome: "Noci", fer: 1, we: 1 },
    { cat: "SCAFFALERIA", color: "var(--cat-scaffaleria)", nome: "Semi Papavero", fer: 0.2, we: 0.2 },
    { cat: "SCAFFALERIA", color: "var(--cat-scaffaleria)", nome: "Pomodori Secchi", fer: 1, we: 1 },
    { cat: "SCAFFALERIA", color: "var(--cat-scaffaleria)", nome: "Carciofi", fer: 1, we: 1 },
    { cat: "SCAFFALERIA", color: "var(--cat-scaffaleria)", nome: "Olive (buste)", fer: 1, we: 1 },
    { cat: "SCAFFALERIA", color: "var(--cat-scaffaleria)", nome: "Capperi", fer: 1, we: 1 },
    { cat: "SCAFFALERIA", color: "var(--cat-scaffaleria)", nome: "Mais", fer: 1, we: 1 },
    { cat: "SCAFFALERIA", color: "var(--cat-scaffaleria)", nome: "Miele", fer: 1, we: 1 },
    { cat: "SCAFFALERIA", color: "var(--cat-scaffaleria)", nome: "Pelati Salsa", fer: 1, we: 1 },
    { cat: "FRESCO", color: "var(--cat-fresco)", nome: "Datterino", fer: 1, we: 2 },
    { cat: "FRESCO", color: "var(--cat-fresco)", nome: "Datt giallo", fer: 1, we: 1 },
    { cat: "FRESCO", color: "var(--cat-fresco)", nome: "Cipolla", fer: 1, we: 2 },
    { cat: "FRESCO", color: "var(--cat-fresco)", nome: "Rucola", fer: 1, we: 2 },
    { cat: "FRESCO", color: "var(--cat-fresco)", nome: "cass. Datterino", fer: 0.5, we: 1 },
    { cat: "FRESCO", color: "var(--cat-fresco)", nome: "Datt. Giallo vaschette", fer: 0.25, we: 0.5 },
    { cat: "FRESCO", color: "var(--cat-fresco)", nome: "cass.Cipolla", fer: 0.25, we: 0.25 },
    { cat: "FRESCO", color: "var(--cat-fresco)", nome: "Basilico", fer: 1, we: 2 },
    { cat: "FRESCO", color: "var(--cat-fresco)", nome: "Menta", fer: 1, we: 1 },
    { cat: "FRESCO", color: "var(--cat-fresco)", nome: "Pere", fer: 1, we: 2 },
    { cat: "PESCE", color: "var(--cat-pesce)", nome: "Acciughe", fer: 1, we: 1 },
    { cat: "PESCE", color: "var(--cat-pesce)", nome: "Tonno (latte)", fer: 1, we: 1 },
    { cat: "PESCE", color: "var(--cat-pesce)", nome: "Salmone", fer: 3, we: 5 },
    { cat: "PESCE", color: "var(--cat-pesce)", nome: "Baccalà", fer: 1, we: 1 },
    { cat: "CONDIMENTI", color: "var(--cat-condimenti)", nome: "Aceto balsamico", fer: 1, we: 1 },
    { cat: "CONDIMENTI", color: "var(--cat-condimenti)", nome: "Origano", fer: 1, we: 1 },
    { cat: "CONDIMENTI", color: "var(--cat-condimenti)", nome: "Sale", fer: 1, we: 1 },
    { cat: "CONDIMENTI", color: "var(--cat-condimenti)", nome: "Olio EVO", fer: 0.5, we: 1 },
    { cat: "CONDIMENTI", color: "var(--cat-condimenti)", nome: "Olio Aglio", fer: 1, we: 1 },
    { cat: "CONDIMENTI", color: "var(--cat-condimenti)", nome: "Olio Piccante", fer: 1, we: 1 },
    { cat: "CONDIMENTI", color: "var(--cat-condimenti)", nome: "Olio Fritte", fer: 1, we: 1 },
    { cat: "FREEZER", color: "var(--cat-freezer)", nome: "Patate Fritte", fer: 1, we: 1 },
    { cat: "FREEZER", color: "var(--cat-freezer)", nome: "Patate al Forno", fer: 1, we: 1 },
    { cat: "FREEZER", color: "var(--cat-freezer)", nome: "Ghiaccio", fer: 2, we: 5 },
    { cat: "IMPASTI", color: "var(--cat-impasti)", nome: "Canapa Bio", fer: 1, we: 1 },
    { cat: "IMPASTI", color: "var(--cat-impasti)", nome: "Semola", fer: 1, we: 1 },
    { cat: "IMPASTI", color: "var(--cat-impasti)", nome: "Lievito", fer: 1, we: 1 },
    { cat: "COMBUSTIBILE", color: "var(--cat-combustibile)", nome: "Legna", fer: 1, we: 2 },
    { cat: "MONETE", color: "var(--cat-monete)", nome: "Rotoli 0,50 €", fer: 1, we: 1 },
    { cat: "MONETE", color: "var(--cat-monete)", nome: "Rotoli 1 €", fer: 1, we: 1 },
    { cat: "MONETE", color: "var(--cat-monete)", nome: "Rotoli 2 €", fer: 1, we: 1 },
    { cat: "MONETE", color: "var(--cat-monete)", nome: "Banc. 5 €", fer: 150, we: 150 },
    { cat: "MONETE", color: "var(--cat-monete)", nome: "Banc. 10 €", fer: 150, we: 150 },
    { cat: "IMBALLAGGI", color: "var(--cat-impasti)", nome: "Pellicola", fer: 1, we: 1 },
    { cat: "IMBALLAGGI", color: "var(--cat-impasti)", nome: "Carta mani", fer: 2, we: 2 },
    { cat: "IMBALLAGGI", color: "var(--cat-impasti)", nome: "Cart.med", fer: 1, we: 2 },
    { cat: "IMBALLAGGI", color: "var(--cat-impasti)", nome: "Cart.mezzi", fer: 1, we: 1 },
    { cat: "IMBALLAGGI", color: "var(--cat-impasti)", nome: "Cart.pers.", fer: 0, we: 0 },
    { cat: "DETERSIVI", color: "var(--cat-detersivi)", nome: "Detergente", fer: 1, we: 1 },
    { cat: "DETERSIVI", color: "var(--cat-detersivi)", nome: "Napisan", fer: 1, we: 1 },
    { cat: "DETERSIVI", color: "var(--cat-detersivi)", nome: "Det. piatti", fer: 1, we: 1 },
    { cat: "DETERSIVI", color: "var(--cat-detersivi)", nome: "Sapone mani", fer: 1, we: 1 },
    { cat: "DETERSIVI", color: "var(--cat-detersivi)", nome: "Ricambi scopa", fer: 1, we: 1 },
    { cat: "DETERSIVI", color: "var(--cat-detersivi)", nome: "Stracci", fer: 1, we: 1 },
    { cat: "DETERSIVI", color: "var(--cat-detersivi)", nome: "Spugne", fer: 1, we: 1 },
    { cat: "DETERSIVI", color: "var(--cat-detersivi)", nome: "Spugne ferro", fer: 1, we: 1 },
    { cat: "BIBITE", color: "var(--cat-bibite)", nome: "Coca Cola N.", fer: 10, we: 10 },
    { cat: "BIBITE", color: "var(--cat-bibite)", nome: "Coca Cola zero N.", fer: 5, we: 5 },
    { cat: "BIBITE", color: "var(--cat-bibite)", nome: "Fanta N.", fer: 0, we: 0 },
    { cat: "BIBITE", color: "var(--cat-bibite)", nome: "Ichnusa non filtrata N.", fer: 5, we: 10 },
    { cat: "BIBITE", color: "var(--cat-bibite)", nome: "Pedavena N.", fer: 5, we: 10 },
    { cat: "BIBITE", color: "var(--cat-bibite)", nome: "Helles N.", fer: 1, we: 2 },
    { cat: "BIBITE", color: "var(--cat-bibite)", nome: "Fred N.", fer: 1, we: 2 },
    { cat: "BIBITE", color: "var(--cat-bibite)", nome: "Bianca N.", fer: 1, we: 2 },
    { cat: "BIBITE", color: "var(--cat-bibite)", nome: "Ipa N.", fer: 1, we: 2 },
    { cat: "BIBITE", color: "var(--cat-bibite)", nome: "Acqua naturale N.", fer: 1, we: 2 },
    { cat: "BIBITE", color: "var(--cat-bibite)", nome: "Acqua frizzante N.", fer: 1, we: 2 },
    { cat: "VARIO", color: "var(--cat-vario)", nome: "Rot. comande", fer: 5, we: 10 },
    { cat: "VARIO", color: "var(--cat-vario)", nome: "Rotoli pos", fer: 2, we: 5 },
    { cat: "VARIO", color: "var(--cat-vario)", nome: "Rotoli scontrini", fer: 2, we: 5 },
    { cat: "VARIO", color: "var(--cat-vario)", nome: "Spazzolaforno", fer: 1, we: 1 },
    { cat: "VARIO", color: "var(--cat-vario)", nome: "Sacchi plastica", fer: 1, we: 2 },
    { cat: "VARIO", color: "var(--cat-vario)", nome: "Sacc. plas picc", fer: 1, we: 1 },
    { cat: "VARIO", color: "var(--cat-vario)", nome: "Sacchi umido", fer: 1, we: 2 },
    { cat: "VARIO", color: "var(--cat-vario)", nome: "Sacc. umi. picc", fer: 1, we: 1 },
    { cat: "VARIO", color: "var(--cat-vario)", nome: "Borsette", fer: 5, we: 10 },
    { cat: "VARIO", color: "var(--cat-vario)", nome: "Gel mani", fer: 0.3, we: 0.5 },
    { cat: "VERDURE CRUDE", color: "var(--cat-crude)", nome: "Melanzane crude", fer: 0, we: 0, noObbligo: true },
    { cat: "VERDURE CRUDE", color: "var(--cat-crude)", nome: "Zucchine crude", fer: 0, we: 0, noObbligo: true },
    { cat: "VERDURE CRUDE", color: "var(--cat-crude)", nome: "Peperoni crudi", fer: 0, we: 0, noObbligo: true },
    { cat: "VERDURE CRUDE", color: "var(--cat-crude)", nome: "Asparagi crudi", fer: 0, we: 0, noObbligo: true },
    { cat: "VERDURE CRUDE", color: "var(--cat-crude)", nome: "Datterino crudo", fer: 0, we: 0, noObbligo: true },
    { cat: "VERDURE CRUDE", color: "var(--cat-crude)", nome: "Datt. Giallo crudo", fer: 0, we: 0, noObbligo: true },
    { cat: "VERDURE CRUDE", color: "var(--cat-crude)", nome: "Rucola cruda", fer: 0, we: 0, noObbligo: true },
    { cat: "VERDURE CRUDE", color: "var(--cat-crude)", nome: "Basilico crudo", fer: 0, we: 0, noObbligo: true },
    { cat: "VERDURE CRUDE", color: "var(--cat-crude)", nome: "Funghi crudi", fer: 0, we: 0, noObbligo: true }
];

const listaBarbazza = ["brie", "gorgonzola", "asiago", "acciughe", "tonno (latte)", "salmone", "bresaola", "carciofi", "olive", "capperi", "semola", "carta mani", "pelati salsa", "cart.med", "cart.mezzi", "lievito"];
const listaMetro = ["ricotta", "no lattosio", "parmigiano 24m", "speck", "mortadella", "prosciutto crudo", "noci", "rot. comande", "rotoli pos", "rotoli scontrini", "spazzolaforno", "pellicola"];
const listaMetroBiban = ["patate fritte", "patate al forno", "olio evo"];
